name: facial_liveness_detection_flutter_plugin
description: 人脸活体检测，支持静默，炫彩，眨眼，张嘴，摇头，点头，远近及随意动作组合，支持Android,IOS,H5,小程序等
version: 1.0.0
homepage: "https://esandinfo.yuque.com/pd7qxf/zd7dgn"

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.esfaceid.facial_liveness_detection_flutter_plugin
        pluginClass: FacialLivenessDetectionFlutterPluginPlugin
      ios:
        pluginClass: FacialLivenessDetectionFlutterPluginPlugin
